### ISSUE TITLE
Problem with funStuff

### ISSUE THREAD

**Issue by Woife5** [Woife5/angry-bot#6]
Nachdem die Variable "funStuff" außerhalb von einer Funktion liegt is die global und des haißt sie wird nur einemal initialisiert wenn der Bot startet.  Des heißt die ganzen random Sachen werden immer nur dann neu initialisiert wenn der Bot neu startet aber dann bleibens immer gleich.

Ich glaub des war so gemeint, dass die jedes mal wenn der Befehl ausgeführt wird neu gewürfelt werden. Dazu müsste die Variable in der execute Funktion zb. drinnen sein.

https://github.com/Woife5/angry-bot/blob/e09d2d613103ee37de6cf371d2b1a267a0f8070b/commands/luhans.js#L56

**Comment by Xovval** [comment]
Ahh, das habe ich glatt an die falsche Stelle verschoben - danke! :)
